import{ENGINE_VERSION,DT,POP,NN_WEIGHTS,WIDTH,TRACK_LIMIT,DEFAULT_TRACK,STRAIGHT,makeTrack,at,spawn,step,breed,randomGenes,angle,clamp}from'./engine.mjs?v=1.4';
const $=id=>document.getElementById(id),canvas=$('race'),ctx=canvas.getContext('2d'),colors=['#c7fa64','#67c4ff','#f5a36d','#c294ff','#ff718c'];
const versionLabel=document.createElement('span');versionLabel.className='version-label';versionLabel.textContent='v'+ENGINE_VERSION;document.querySelector('footer').append(versionLabel);
const sectorComparison=document.createElement('span');sectorComparison.className='sector-comparison';sectorComparison.hidden=true;document.querySelector('.track-footer').append(sectorComparison);
const personalBestComparison=document.createElement('div');personalBestComparison.className='personal-best-comparison';document.querySelector('#best').parentElement.insertBefore(personalBestComparison,document.querySelector('#championNote'));
let custom=DEFAULT_TRACK.map(p=>[...p]),track=makeTrack(custom),agents=[],generation=1,history=[],champion=null,playerBest=null,running=false,mode='training',editing=false,draft=[],visible=[],replaying=false,replayTime=0,manual=null,keys=new Set(),last=0,accumulator=0,lastUI=0,simTime=0,carSpeed=125,activeTrack=2,tracks={},saveTimer,openArea=false,cornerRadius=52,draftCornerRadius=52;
function notify(s){$('notice').textContent=s;clearTimeout(saveTimer);saveTimer=setTimeout(()=>$('notice').textContent='',4500);}
function validPoints(p){return Array.isArray(p)&&p.length>=2&&p.length<=24&&p.every(v=>Array.isArray(v)&&v.length===2&&v.every(Number.isFinite))&&makeTrack(p).length>=300;}
function savedRadius(value){return Number.isFinite(value)?clamp(value,0,120):52;}
function blankTrack(points,radius=cornerRadius){return{custom:points.map(p=>[...p]),cornerRadius:radius,generation:1,history:[],champion:null,playerBest:null,genes:[]};}
function snapshot(){return{custom:custom.map(p=>[...p]),cornerRadius,generation,history:history.slice(-300),champion,playerBest,genes:agents.map(a=>[...a.genes])};}
function save(){if(openArea)return;tracks[activeTrack]=snapshot();try{localStorage.setItem('apex-evolution-v1',JSON.stringify({version:2,activeTrack,carSpeed,tracks}));}catch{notify('Browser storage is unavailable or full. Your tracks work in this session but may not survive a reload.');}}
function loadSlot(number){const d=tracks[number];activeTrack=number;custom=d.custom.map(p=>[...p]);cornerRadius=savedRadius(d.cornerRadius);track=makeTrack(custom,cornerRadius);generation=Number.isInteger(d.generation)&&d.generation>0?d.generation:1;history=Array.isArray(d.history)?d.history.filter(h=>Number.isFinite(h.gen)&&Number.isInteger(h.count)&&(h.best===null||Number.isFinite(h.best))&&(h.avg===null||Number.isFinite(h.avg))):[];champion=null;const c=d.champion;if(c&&Number.isFinite(c.time)&&c.time>0&&Array.isArray(c.trace)&&c.trace.length>1&&c.trace.every(p=>Array.isArray(p)&&p.length===3&&p.every(Number.isFinite)))champion=c;agents=[];if(Array.isArray(d.genes)&&d.genes.length===POP&&d.genes.every(g=>Array.isArray(g)&&(g.length===NN_WEIGHTS||g.length===5||g.length===5+track.lineStations.length-2)&&g.every(Number.isFinite)))agents=d.genes.map((g,i)=>spawn(track,g,i));if(!agents.length)newPopulation();else sample();simTime=0;accumulator=0;running=false;replaying=false;keys.clear();}
function refreshTrackMenu(){$('trackSelect').innerHTML=Object.keys(tracks).map(Number).sort((a,b)=>a-b).map(n=>'<option value="'+n+'">Track '+n+'</option>').join('');$('trackSelect').value=String(activeTrack);}
if(!localStorage.getItem('apex-evolution-rounded-reset')){localStorage.removeItem('apex-evolution-v1');localStorage.setItem('apex-evolution-rounded-reset','1');}
try{const d=JSON.parse(localStorage.getItem('apex-evolution-v1'));if(d){carSpeed=Number.isFinite(d.carSpeed)?clamp(Math.round(d.carSpeed/25)*25,25,300):125;if(d.version===2&&d.tracks&&typeof d.tracks==='object'){for(const [key,value]of Object.entries(d.tracks)){const n=Number(key);if(Number.isInteger(n)&&n>=1&&n<=999&&validPoints(value?.custom))tracks[n]=value;}activeTrack=tracks[d.activeTrack]?Number(d.activeTrack):Number(Object.keys(tracks)[0]||2);}else if(validPoints(d.custom)){tracks[1]=blankTrack(STRAIGHT);tracks[2]=d;activeTrack=2;}}}catch{notify('Could not load saved tracks. Starting with the default tracks.');}
if(!Object.keys(tracks).length){tracks={1:blankTrack(STRAIGHT),2:blankTrack(DEFAULT_TRACK)};activeTrack=2;}
loadSlot(activeTrack);playerBest=Number.isFinite(tracks[activeTrack]?.playerBest)&&tracks[activeTrack].playerBest>0?tracks[activeTrack].playerBest:null;cornerRadius=savedRadius(tracks[activeTrack]?.cornerRadius);refreshTrackMenu();
const openAreaButton=document.createElement('button');openAreaButton.textContent='Open area';openAreaButton.id='openArea';$('trackSelect').parentElement.insertBefore(openAreaButton,$('edit'));
const exitOpenAreaButton=document.createElement('button');exitOpenAreaButton.textContent='Exit open area';exitOpenAreaButton.id='exitOpenArea';exitOpenAreaButton.className='open-area-exit';exitOpenAreaButton.hidden=true;$('race').parentElement.append(exitOpenAreaButton);
const radiusField=document.createElement('label');radiusField.className='corner-radius-control';radiusField.htmlFor='cornerRadius';radiusField.textContent='Corner radius ';const radiusValue=document.createElement('output');radiusValue.textContent='52 px';const radiusInput=document.createElement('input');radiusInput.id='cornerRadius';radiusInput.type='range';radiusInput.min='0';radiusInput.max='120';radiusInput.step='1';radiusInput.value='52';radiusField.append(radiusInput,radiusValue);$('editor').prepend(radiusField);radiusInput.oninput=()=>{draftCornerRadius=Number(radiusInput.value);radiusValue.textContent=draftCornerRadius+' px';draw();};
function enterOpenArea(){save();openArea=true;custom=[[80,80],[980,80],[980,460],[80,460],[80,80]];track=makeTrack(custom);track.openArea=true;mode='practice';running=false;editing=false;replaying=false;manual=spawn(track,[0,0,0,0,0]);track.points=[];keys.clear();document.body.classList.add('open-area-mode');$('trackSelect').disabled=true;switchMode('practice');}
function exitOpenArea(){openArea=false;document.body.classList.remove('open-area-mode');$('trackSelect').disabled=false;loadSlot(activeTrack);switchMode('practice');}
const rawLoadSlot=loadSlot;loadSlot=number=>{rawLoadSlot(number);playerBest=Number.isFinite(tracks[number]?.playerBest)&&tracks[number].playerBest>0?tracks[number].playerBest:null;cornerRadius=savedRadius(tracks[number]?.cornerRadius);};
openAreaButton.onclick=enterOpenArea;exitOpenAreaButton.onclick=exitOpenArea;
$('trackSelect').onchange=()=>{const number=Number($('trackSelect').value);if(!tracks[number])return;if(editing&&!confirm('Discard unsaved track edits?')){$('trackSelect').value=String(activeTrack);return;}save();editing=false;$('editor').hidden=true;loadSlot(number);switchMode(mode);save();drawChart();$('trackSelect').blur();};
function sample(){const ids=agents.map(a=>a.id);for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]];}visible=ids.slice(0,5);}
function newPopulation(){simTime=0;agents=Array.from({length:POP},(_,i)=>spawn(track,randomGenes(Math.random,track),i));sample();}
if(!agents.length)newPopulation();else sample();
function finishGeneration(){const finishers=agents.filter(a=>a.finished),times=finishers.map(a=>a.time),best=times.length?Math.min(...times):null;history.push({gen:generation,best,avg:times.length?times.reduce((a,b)=>a+b,0)/times.length:null,count:times.length});if(history.length>300)history.shift();if(best!==null&&(!champion||best<champion.time)){const a=finishers.find(a=>a.time===best);champion={time:a.time,trace:a.trace,sectorTimes:a.sectorTimes,genes:a.genes,generation,speedMin:a.speedMin??125,speedMax:a.speedMax??125};}agents=breed(agents,track);simTime=0;generation++;sample();save();drawChart();update();}
function toggle(){if(editing)return;replaying=false;if(mode==='practice'){running=false;keys.clear();if(!manual||!manual.alive)manual=spawn(track,[0,0,0,0,0]);}else running=!running;accumulator=0;last=performance.now();update();}
function driveInput(key,fresh){keys.add(key);if(mode==='practice'&&!editing&&!running&&fresh&&(key==='w'||key==='ArrowUp')){if(!manual||!manual.alive)manual=spawn(track,[0,0,0,0,0]);running=true;replaying=false;accumulator=0;last=performance.now();update();}}
$('start').onclick=toggle;
function switchMode(next){if(editing)return;running=false;replaying=false;keys.clear();mode=next;manual=next==='practice'?spawn(track,[0,0,0,0,0]):null;$('trainingTab').classList.toggle('selected',next==='training');$('practiceTab').classList.toggle('selected',next==='practice');$('driveHelp').hidden=next!=='practice';$('speed').disabled=next==='practice';$('edit').disabled=false;$('reset').disabled=next==='practice';$('trackName').textContent='Track '+activeTrack;$('trackMeta').textContent=Math.round(track.length)+' px · Shared by you and the AI';$('controlHelp').textContent=next==='practice'?'Press W or ↑ to start driving and the timer together. Release and press again after finishing to retry.':'Each generation keeps its strongest drivers and explores new driving styles.';update();draw();}
$('trainingTab').onclick=()=>switchMode('training');$('practiceTab').onclick=()=>switchMode('practice');
$('replay').onclick=()=>{if(!champion||editing)return;switchMode('training');running=false;replaying=true;replayTime=0;update();};
$('reset').onclick=()=>{if(!confirm('Reset training and delete the saved champion for this course?'))return;running=false;replaying=false;generation=1;history=[];champion=null;newPopulation();save();drawChart();update();draw();};
function openEditor(isNew=false){if(editing&&!confirm('Discard unsaved track edits?'))return;let number=activeTrack;if(isNew){number=1;while(tracks[number]&&number<=999)number++;if(number>999)return notify('All 999 track numbers are in use. Edit an existing track to replace it.');}running=false;replaying=false;editing=true;draft=isNew?[]:custom.map(p=>[...p]);$('editor').hidden=false;$('saveTrackNumber').value=String(number);draftCornerRadius=cornerRadius;$('cornerRadius').value=String(draftCornerRadius);radiusValue.textContent=draftCornerRadius+' px';keys.clear();update();draw();if(isNew)notify('Draw your new course, then choose Save track.');}
$('edit').onclick=()=>openEditor();
$('addTrack').onclick=()=>openEditor(true);
function closeEditor(){editing=false;$('editor').hidden=true;update();draw();}
$('cancelEdit').onclick=closeEditor;$('clear').onclick=()=>{draft=[];draw();};$('undo').onclick=()=>{draft.pop();draw();};
let dragIndex=-1;
const editorPoint=e=>{const r=canvas.getBoundingClientRect();return[clamp((e.clientX-r.left)*1060/r.width,50,1010),clamp((e.clientY-r.top)*540/r.height,50,490)];};
canvas.addEventListener('pointerdown',e=>{if(!editing)return;const p=editorPoint(e);dragIndex=draft.findIndex(point=>Math.hypot(point[0]-p[0],point[1]-p[1])<=18);if(dragIndex>=0){canvas.setPointerCapture(e.pointerId);return;}if(draft.length&&Math.hypot(p[0]-draft.at(-1)[0],p[1]-draft.at(-1)[1])<75)return notify('Space your points at least 75 px apart.');if(draft.length>=24)return notify('Use up to 24 points per track.');draft.push(p);draw();});
canvas.addEventListener('pointermove',e=>{if(!editing||dragIndex<0)return;draft[dragIndex]=editorPoint(e);draw();});
canvas.addEventListener('pointerup',e=>{if(dragIndex>=0&&canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);dragIndex=-1;});
canvas.addEventListener('pointercancel',()=>{dragIndex=-1;});
function intersects(a,b,c,d){const cross=(p,q,r)=>(q[0]-p[0])*(r[1]-p[1])-(q[1]-p[1])*(r[0]-p[0]);return cross(a,b,c)*cross(a,b,d)<=0&&cross(c,d,a)*cross(c,d,b)<=0;}
$('apply').onclick=()=>{const number=Number($('saveTrackNumber').value);if(!Number.isInteger(number)||number<1||number>999)return notify('Choose a whole track number from 1 to 999.');if(draft.length<2)return notify('Place at least two points for a track.');for(let i=1;i<draft.length;i++)for(let j=i+2;j<draft.length;j++)if(intersects(draft[i-1],draft[i],draft[j-1],draft[j]))return notify('Avoid crossing track segments. Undo or move back to an earlier point.');const candidate=makeTrack(draft,draftCornerRadius);if(candidate.length<300)return notify('Make the course at least 300 px long.');const same=tracks[number]&&JSON.stringify(tracks[number].custom)===JSON.stringify(draft)&&savedRadius(tracks[number].cornerRadius)===draftCornerRadius;if(tracks[number]&&!same&&!confirm('Replace Track '+number+'? Its AI progress and champion will reset. Other tracks will be kept.'))return;save();if(!same)tracks[number]=blankTrack(draft,draftCornerRadius);editing=false;$('editor').hidden=true;loadSlot(number);refreshTrackMenu();switchMode(mode);save();drawChart();notify('Track '+number+' saved. You and the AI can both drive it.');};
const relevant=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'];
const normalizeKey=key=>key.length===1?key.toLowerCase():key;
window.addEventListener('keydown',e=>{const key=normalizeKey(e.key);if(mode!=='practice'||editing||!relevant.includes(key)||e.ctrlKey||e.metaKey||e.altKey||e.target?.isContentEditable||['INPUT','SELECT','TEXTAREA'].includes(e.target?.tagName))return;e.preventDefault();driveInput(key,!e.repeat&&!keys.has(key));});
window.addEventListener('keyup',e=>keys.delete(normalizeKey(e.key)));
window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{last=0;accumulator=0;keys.clear();});
for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);driveInput(b.dataset.key,!keys.has(b.dataset.key));};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys.delete(b.dataset.key);}
function update(){$('trackName').textContent='Track '+activeTrack;$('trackMeta').textContent=Math.round(track.length)+' px · Shared by you and the AI';$('visibleLegend').textContent=mode==='practice'?'Your car':'Five random racers';$('carSpeed').value=String(carSpeed);$('carSpeedValue').textContent=carSpeed+' px/s';$('speedLimit').textContent=carSpeed+' px/s';const h=history.at(-1),num=v=>v==null?'—':v.toFixed(2);$('generation').textContent='GEN '+String(generation).padStart(3,'0');$('status').textContent=editing?'TRACK EDITOR':replaying?'CHAMPION REPLAY':running?'SESSION RUNNING':mode==='practice'?'READY TO DRIVE':'SESSION PAUSED';$('start').innerHTML=(mode==='practice'?(running?'Pause drive':!manual||manual.alive?'Press W or ↑ to drive':'Reset run'):(running?'Pause training':'Start training'))+' <span>'+(running?'Ⅱ':'▶')+'</span>';$('start').disabled=editing;$('best').innerHTML=num(champion?.time)+'<small> s</small>';$('championNote').textContent=champion?'Champion from generation '+champion.generation+' · '+(champion.speedMin??125)+((champion.speedMax??125)!==(champion.speedMin??125)?'–'+champion.speedMax:'')+' px/s · saved in this browser':'Your first finisher sets the benchmark.';$('lastBest').innerHTML=num(h?.best)+'<small> s</small>';$('average').innerHTML=num(h?.avg)+'<small> s</small>';$('completed').innerHTML=(h?.count||0)+'<small> / 50</small>';$('alive').innerHTML=agents.filter(a=>a.alive).length+'<small> / 50</small>';$('replay').disabled=!champion||editing;$('clock').textContent=(replaying?replayTime:mode==='practice'?manual?.time||0:simTime).toFixed(2)+' s';$('runOverlay').textContent=editing?'Click to add track points':replaying?'Champion replay · '+champion.time.toFixed(2)+' s':mode==='practice'&&!manual?.alive?(manual?.finished?'Finished in '+manual.time.toFixed(2)+' s · Press W to retry':manual?.stopReason==='timeout'?'Time limit reached · Press W to retry':'Center crossed boundary · Press W to retry'):running?mode==='practice'?'Manual drive':$('speed').value==='headless'?'Training at maximum speed · animation off':'Generation '+generation+' in motion':mode==='practice'?'Press W or ↑ · timer starts when you drive':'Ready when you are';}
const baseUpdate=update;update=()=>{baseUpdate();$('trackName').textContent=openArea?'Open area':'Track '+activeTrack;$('trackMeta').textContent=openArea?'Free drive · no start or finish':Math.round(track.length)+' px · Shared by you and the AI';$('clock').textContent=openArea?'OPEN':$('clock').textContent;$('start').hidden=openArea;$('openArea').hidden=openArea;$('exitOpenArea').hidden=!openArea;$('trackSelect').hidden=openArea;$('edit').hidden=openArea;$('addTrack').hidden=openArea;$('showDiagnostics').hidden=openArea;$('ghost').disabled=openArea;};
function path(points){
 ctx.beginPath();
 if(!points.length)return;
 ctx.moveTo(...points[0]);
 for(let i=1;i<points.length;i++)ctx.lineTo(...points[i]);
}
function drawCar(p,color,ghost=false){ctx.save();ctx.translate(p[0],p[1]);ctx.rotate(p[2]);ctx.globalAlpha=ghost?.4:1;ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=ghost?0:9;ctx.fillRect(-10,-5,20,10);ctx.shadowBlur=0;ctx.fillStyle='#1a2934';ctx.fillRect(0,-4,4,8);ctx.fillStyle='#dfe9eb';ctx.fillRect(7,-4,2,2);ctx.fillRect(7,2,2,2);ctx.beginPath();ctx.arc(0,0,2,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.restore();}
function ghostAt(time){const f=Math.min(time/.05,champion.trace.length-1),i=Math.floor(f),a=champion.trace[i],b=champion.trace[Math.min(i+1,champion.trace.length-1)],v=f-i;return[a[0]+(b[0]-a[0])*v,a[1]+(b[1]-a[1])*v,a[2]+angle(b[2]-a[2])*v];}
function draw(){ctx.fillStyle='#0f1920';ctx.fillRect(0,0,1060,540);ctx.strokeStyle='#1a2933';ctx.lineWidth=1;for(let x=0;x<1060;x+=30){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,540);ctx.stroke();}for(let y=0;y<540;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1060,y);ctx.stroke();}const t=editing?makeTrack(draft,draftCornerRadius):track,points=t.points;ctx.lineJoin='round';ctx.lineCap='round';if(points.length>1){path(points);ctx.strokeStyle='#794e37';ctx.lineWidth=WIDTH+8;ctx.stroke();path(points);ctx.strokeStyle='#f6cd64';ctx.lineWidth=2*TRACK_LIMIT+4;ctx.stroke();path(points);ctx.strokeStyle='#263540';ctx.lineWidth=2*TRACK_LIMIT;ctx.stroke();path(points);ctx.setLineDash([7,14]);ctx.strokeStyle='#60717e';ctx.lineWidth=1;ctx.stroke();ctx.setLineDash([]);const drawn=t;for(const [s,label]of[[0,'START'],[drawn.length,'FINISH']]){const p=at(drawn,s);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.heading);for(let x=0;x<2;x++)for(let y=0;y<8;y++){ctx.fillStyle=(x+y)%2?'#d6e1e7':'#16232e';ctx.fillRect(x*5-5,y*8-32,5,8);}ctx.restore();ctx.fillStyle='#9bb0bf';ctx.font='12px Arial';ctx.fillText(label,p.x-20,p.y+55);}}
if(editing){draft.forEach((p,i)=>{ctx.fillStyle='#c7fa64';ctx.beginPath();ctx.arc(...p,5,0,Math.PI*2);ctx.fill();ctx.font='13px Arial';ctx.fillText(i+1,p[0]+9,p[1]-9);});return;}if(champion&&($('ghost').checked||replaying)){path(champion.trace.map(p=>[p[0],p[1]]));ctx.strokeStyle='#c7fa6477';ctx.lineWidth=2;ctx.setLineDash([5,7]);ctx.stroke();ctx.setLineDash([]);}if(champion&&($('ghost').checked||replaying))drawCar(ghostAt(replaying?replayTime:mode==='practice'?manual?.time||0:simTime),'#eef7ff',true);if(mode==='practice'){if(manual){drawCar([manual.x,manual.y,manual.heading],manual.stopReason==='off-track'?'#ff718c':colors[0]);if(manual.stopReason==='off-track'){ctx.strokeStyle='#ff718c';ctx.lineWidth=2;ctx.beginPath();ctx.arc(manual.x,manual.y,14,0,Math.PI*2);ctx.stroke();}}return;}if(!replaying)visible.forEach((id,i)=>{const a=agents[id];if(a){ctx.globalAlpha=a.alive?1:.4;drawCar([a.x,a.y,a.heading],colors[i]);ctx.globalAlpha=1;}});}
function drawChart(){const c=$('chart'),g=c.getContext('2d'),w=c.width,h=c.height;g.clearRect(0,0,w,h);const data=history.slice(-100),vals=data.flatMap(d=>[d.best,d.avg]).filter(v=>v!==null);$('chartEmpty').hidden=vals.length>0;g.font='13px Arial';g.fillStyle='#94a1ad';g.strokeStyle='#2b3944';if(!vals.length)return;let lo=Math.floor(Math.min(...vals)*.9),hi=Math.ceil(Math.max(...vals)*1.1);if(hi===lo)hi++;const x=i=>60+i*(w-100)/Math.max(1,data.length-1),y=v=>20+(hi-v)/(hi-lo)*125;for(let i=0;i<4;i++){const v=lo+(hi-lo)*i/3;g.beginPath();g.moveTo(55,y(v));g.lineTo(w-20,y(v));g.stroke();g.fillText(v.toFixed(1)+'s',6,y(v)+4);}for(const [key,color]of[['avg','#63baff'],['best','#c7fa64']]){g.strokeStyle=color;g.lineWidth=2;g.beginPath();let active=false;data.forEach((d,i)=>{if(d[key]===null){active=false;return;}if(active)g.lineTo(x(i),y(d[key]));else g.moveTo(x(i),y(d[key]));active=true;});g.stroke();data.forEach((d,i)=>{if(d[key]!==null){g.fillStyle=color;g.beginPath();g.arc(x(i),y(d[key]),2.5,0,Math.PI*2);g.fill();}});}g.fillStyle='#94a1ad';g.fillText('Gen '+data[0].gen,55,171);g.fillText('Gen '+data.at(-1).gen,w-90,171);}
function tick(){if(mode==='practice'){step(manual,track,{turn:(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0),throttle:keys.has('ArrowUp')||keys.has('w')?1:keys.has('ArrowDown')||keys.has('s')?-1:0},carSpeed);if(!manual.alive){if(manual.finished&&(!playerBest||manual.time<playerBest)){playerBest=manual.time;save();}running=false;}updateSectorComparison();}else{simTime+=DT;agents.forEach(a=>step(a,track,undefined,carSpeed));if(agents.every(a=>!a.alive))finishGeneration();}}
function loop(now){const delta=last?Math.min((now-last)/1000,.1):0;last=now;if(replaying){replayTime=Math.min(replayTime+delta,champion.time);if(replayTime>=champion.time)replaying=false;draw();}else if(running&&!editing){if(mode==='training'&&$('speed').value==='headless'){const until=performance.now()+9;do{tick();}while(performance.now()<until&&running);}else{accumulator+=delta*(mode==='practice'?1:Number($('speed').value));let steps=0;while(accumulator>=DT&&steps++<240&&running){tick();accumulator-=DT;}draw();}}else draw();updateSectorComparison();updatePersonalBest();if(now-lastUI>150){update();lastUI=now;}requestAnimationFrame(loop);}
$('carSpeed').oninput=()=>{const value=Number($('carSpeed').value);if(!Number.isFinite(value))return;carSpeed=clamp(Math.round(value/25)*25,25,300);agents.forEach(a=>{if(a.alive)a.speed=Math.min(a.speed,carSpeed);});if(manual?.alive)manual.speed=Math.min(manual.speed,carSpeed);update();};$('carSpeed').onchange=save;
$('speed').onchange=()=>{accumulator=0;draw();update();};$('ghost').onchange=draw;window.addEventListener('pagehide',save);
if(document.modelContext?.registerTool){for(const tool of[{name:'get_training_status',description:'Read current generation, completion results, and champion time.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({trackNumber:activeTrack,generation,running,mode,championTime:champion?.time??null,lastGeneration:history.at(-1)??null})},{name:'set_training_running',description:'Start or pause AI training on the selected track.',inputSchema:{type:'object',properties:{running:{type:'boolean'}},required:['running'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(typeof input?.running!=='boolean'||editing)throw Error('Provide a boolean running value and close the track editor first.');switchMode('training');if(input.running)toggle();return{running,generation};}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}
function updateSectorComparison(){const visible=mode==='practice'&&!openArea;sectorComparison.hidden=!visible;if(!visible)return;const player=manual?.sectorTimes||[],ai=champion?.sectorTimes||[];const format=(times)=>times.length?times.map((time,index)=>`S${index+1} ${time.toFixed(2)}${ai[index]!==undefined?`/${ai[index].toFixed(2)}`:''}`).join(' · '):'S1 -- · S2 -- · S3 --';sectorComparison.textContent=`${format(player)}${champion?` | AI ${champion.time.toFixed(2)}s`:' | AI pending'}${manual?.finished?` | Total ${manual.time.toFixed(2)}s`:''}`;}
function updatePersonalBest(){personalBestComparison.textContent=`YOUR BEST  ${playerBest?playerBest.toFixed(2)+' s':'--'}    AI BEST  ${champion?champion.time.toFixed(2)+' s':'--'}`;}
update();draw();drawChart();updatePersonalBest();requestAnimationFrame(loop);

$('exportDiagnostics').onclick=()=>{const field=$('diagnosticData');field.value=JSON.stringify({build:ENGINE_VERSION,trackNumber:activeTrack,carSpeed,...snapshot()});field.hidden=false;field.focus();field.select();};

$('showDiagnostics').onclick=()=>{$('diagnostics').open=true;$('exportDiagnostics').onclick();$('diagnostics').scrollIntoView({block:'center'});};
